config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://127.0.0.1:52858'
  phases:
    - duration: 10
      arrivalRate: 5
      name: "Prueba rendimiento Login / Registro F1"
    - duration: 10
      arrivalRate: 5
      rampTo: 10
      name: "Prueba rendimiento Login / Registro F2"
    - duration: 10
      arrivalRate: 10
      rampTo: 5
      name: "Prueba rendimiento Login / Registro F3"
scenarios:
  - name: "Sessions Flow (registro + login)"
    flow:
      - log: "Creamos las variables para el usuario de prueba"
      - get:
          url: "/usuario"
          capture:
            - json: "$.usuario.nombre"
              as: "nombre"
            - json: "$.usuario.apellido"
              as: "apellido"
            - json: "$.usuario.email"
              as: "email"
            - json: "$.usuario.password"
              as: "password"
      - log: "Registro de usuario {{nombre}} {{apellido}}"
      - post:
          url: "/api/sessions/registro"
          json:
            nombre: "{{nombre}}"
            apellido: "{{apellido}}"
            email: "{{email}}"
            password: "{{password}}"
      - think: 2
      - log: "Login {{email}}"
      - post:
          url: "/api/sessions/login"
          json:
            email: "{{email}}"
            password: "{{password}}"
